import Link from "next/link";
import Image from "next/image";
import { ArrowUpRight, ArrowRight, Coffee, Timer, Heart, SlidersHorizontal } from "lucide-react";

const paths = [
  { n: "01", title: "Find your flavour.", text: "A few things you love. A coffee that feels like you.", href: "/tasteprint", image: "/products/guji-reserve.webp", label: "Discover your Tasteprint", cls: "flavour" },
  { n: "02", title: "Make it your own.", text: "Origin, drink, milk, finish. Every little detail, yours.", href: "/origin-bar", image: "/menu/deldiet-hot-cup.webp", label: "Step into the Origin Bar", cls: "craft" },
  { n: "03", title: "Bring the ritual home.", text: "Coffee, thoughtful objects, and the tools to brew beautifully.", href: "/shop", image: "/products/home-kit.webp", label: "Explore the collection", cls: "home" },
];

export default function HomeCollection() {
  return <>
    <section className="dd-world" aria-labelledby="world-title">
      <div className="dd-section-heading"><div><p className="eyebrow">A world of coffee. A place for you.</p><h2 id="world-title">Good coffee.<br/><em>Endless possibility.</em></h2></div><p>For your first sip, your next discovery, and the ritual you keep coming back to. Follow your curiosity.</p></div>
      <div className="dd-paths">{paths.map(p => <Link href={p.href} className={`dd-path dd-path-${p.cls}`} key={p.n}><div className="dd-path-image"><Image src={p.image} alt="" fill unoptimized sizes="(max-width: 760px) 100vw, 33vw"/><span>{p.n} / THE DELDIET WORLD</span><ArrowUpRight size={24}/></div><div className="dd-path-copy"><h3>{p.title}</h3><p>{p.text}</p><b>{p.label}<ArrowRight size={18}/></b></div></Link>)}</div>
    </section>
    <section className="dd-origin-story"><div className="dd-origin-picture"><Image src="/origin-exchange-hero.png" alt="Coffee growing landscape and sourcing journey" fill unoptimized sizes="(max-width: 760px) 100vw, 50vw"/><span>THE ORIGIN EDIT / 01</span></div><div className="dd-origin-copy"><p className="eyebrow">Curiosity starts somewhere</p><h2>Before the cup,<br/><em>there’s a world.</em></h2><p>Bright Ethiopian florals. Colombia’s rounded sweetness. The depth of an Indonesian cup. Explore the places, processes, and flavour profiles that make coffee wonderfully different.</p><div className="dd-origin-stats"><div><b>18</b><span>Origin profiles</span></div><div><b>3</b><span>Growing regions</span></div><div><b>You</b><span>The next chapter</span></div></div><Link href="/origins" className="button button-lime">Explore the origin atlas<ArrowUpRight size={20}/></Link><small>Explore concept profiles, with evidence and verification status shown.</small></div></section>
    <section className="dd-brew-banner"><div><p className="eyebrow">Introducing the Brew Studio</p><h2>A better morning,<br/><em>one small adjustment away.</em></h2><p>Dial in a recipe. Follow the brew timer. Note what you taste. Keep the cups you love and make them again.</p><Link href="/brew-lab" className="button button-dark">Start a brew<ArrowUpRight size={20}/></Link></div><div className="dd-brew-preview"><div className="dd-mini-heading"><Coffee size={21}/><span>YOUR DAILY RITUAL</span><span>POUR-OVER</span></div><div className="dd-brew-time">03<span>:</span>00<small>A little time. A lovely cup.</small></div><div className="dd-brew-spec"><span><b>20 g</b>Coffee</span><span><b>320 g</b>Water</span><span><b>1:16</b>Ratio</span></div><Link href="/brew-lab">Make this recipe yours<ArrowRight size={20}/></Link></div></section>
    <section className="dd-coffeehouse"><Image src="/deldiet-cafe-interior.png" alt="Warm Deldiet coffeehouse interior" fill unoptimized sizes="100vw"/><div><p className="eyebrow light">The coffeehouse / St. John’s, Newfoundland</p><h2>Your kind<br/><em>of coffee place.</em></h2><p>Come for a cup. Stay for the conversation. Explore our coffeehouse concept and the menu we’re bringing together.</p><Link href="/coffeehouse" className="button button-light">Meet the coffeehouse<ArrowUpRight size={20}/></Link><small>Opening date and location to be announced.</small></div></section>
    <section className="dd-passport-invite"><div><p className="eyebrow">Your coffee life, together</p><h2>A little more<br/><em>you in every cup.</em></h2></div><div><p>Your preferences, favourite finds, saved Brewprints, and brewing notes. A personal coffee collection that grows with your curiosity.</p><div className="dd-passport-perks"><span><SlidersHorizontal size={18}/>Taste preferences</span><span><Heart size={18}/>Saved favourites</span><span><Timer size={18}/>Brew journal</span></div><Link className="button button-dark" href="/passport">Open your Passport<ArrowUpRight size={20}/></Link><Link className="dd-inline-link" href="/my-collection">See your collection</Link></div></section>
  </>;
}
